name: Generate Docs

on: 
  push:
    branches: [ main, pts ]
#  pull_request:
#    branches: [ main ]

jobs:
  codex:
    name: Generate Codex
    runs-on: ubuntu-latest

    env:
      LDOC_CONFIG: "${{ github.ref == 'refs/heads/pts' && 'config-pts.ld' || 'config.ld' }}"
      CODEX_SUFFIX: "${{ github.ref == 'refs/heads/pts' && 'codex-pts' || 'codex' }}"

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: leafo/gh-actions-lua@v9.1.0

      - uses: leafo/gh-actions-luarocks@v4.3.0

      - name: Setup
        run: |
          luarocks install ldoc
          mkdir docs

      - name: Build mock codex
        run: |
          ldoc -c $LDOC_CONFIG .
          mv doc docs/mock-codex
      
      - name: Remove mock methods
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '--- Mock'
          replace: '-- Mock'
          regex: false
          include: src/dumocks/*.lua

      - name: Build web codex
        run: |
          ldoc -c $LDOC_CONFIG .
          mv doc docs/web-codex
      
      - name: Clean up CSS
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'width: 700px;'
          replace: ';'
          regex: false
          include: docs/**/ldoc.css

      - name: Deploy Web Codex
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: codex
          folder: docs/web-codex
          target-folder: web-${{ env.CODEX_SUFFIX }}

      - name: Deploy Mock Codex
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: codex
          folder: docs/mock-codex
          target-folder: mock-${{ env.CODEX_SUFFIX }}
