name: Publish to LuaRocks

on: 
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: leafo/gh-actions-lua@v9.1.0

      - uses: leafo/gh-actions-luarocks@v4.3.0

      - run: luarocks install dkjson

      - run: luarocks upload --api-key ${{ secrets.API_KEY }}  rockspecs/du-mocks-${GITHUB_REF##*/v}-1.rockspec
