name: Test

on: 
  push:
    branches: [ main, pts ]
  pull_request:
    branches: [ main ]

jobs:
  luarocks:
    name: Test LuaRocks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10.0.0

      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4.3.0

      - name: Setup
        run: |
          luarocks install --only-deps du-mocks-scm-0.rockspec

      - name: Verify LuaRocks config
        run: luarocks make

  ldoc:
    name: Test LDoc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10.0.0

      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4.3.0

      - name: Setup
        run: |
          luarocks install --only-deps du-mocks-scm-0.rockspec
          luarocks install ldoc

      - name: Verify codex builds cleanly
        run: ldoc . --fatalwarnings

      - name: Verify PTS codex builds cleanly
        run: ldoc -c config-pts.ld . --fatalwarnings

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
#        luaVersion: [ "5.3" ]
        luaVersion: [ "5.3", "5.4" ]

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4.3.0

      - name: Setup
        run: |
          luarocks install --only-deps du-mocks-scm-0.rockspec
          luarocks install luaunit
          luarocks install luacov
          luarocks install luafilesystem

      - name: Test
        run: ./test/runTests.sh -o junit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@82082dac68ad6a19d980f8ce817e108b9f496c2a # v2.17.1
        if: always()
        with:
          junit_files: "test/results/**/*.xml"

      - run: luacov

      - name: Upload to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        if: ${{ matrix.luaVersion == '5.3' }}

      - name: Export In-Game Tests
        run: ./test/exportAll.sh

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: ${{ matrix.luaVersion == '5.3' }}
        with:
          name: test_configs
          path: |
            test/configExports
            test/results/*.html

      - run: rm -f test/results/*.xml

      - name: Deploy Screen Renderer Output
        uses: JamesIves/github-pages-deploy-action@a96ffa23204731ec64e3e1316072197d98bfbaea # v4.6.6
        if: ${{ matrix.luaVersion == '5.3' && (github.event_name == 'push' && github.ref_name == 'main') }}
        with:
          branch: codex
          folder: test/results
          target-folder: test-results
